/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import entidades.Cliente;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class BuscarCliente extends javax.swing.JInternalFrame {

    private int count ;
    public BuscarCliente() {
        initComponents();
        count = 0 ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtApellido1 = new javax.swing.JTextField();
        jtDni1 = new javax.swing.JTextField();
        jtNombre1 = new javax.swing.JTextField();
        jtCiudad1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtTelefono1 = new javax.swing.JTextField();
        jcantCoinc = new javax.swing.JLabel();
        jbSig = new javax.swing.JButton();
        jbAnt = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInputActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BUSCAR CLIENTE POR:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setAlignmentY(0.0F);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APELLIDO", "CIUDAD", "TELEFONO" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("COINCIDENCIAS:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("DNI:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("DIRECCION:");

        jtDireccion.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("NOMBRE:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("APELLIDO:");

        jtApellido1.setEditable(false);
        jtApellido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtApellido1.setPreferredSize(new java.awt.Dimension(110, 26));
        jtApellido1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellido1ActionPerformed(evt);
            }
        });

        jtDni1.setEditable(false);
        jtDni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtDni1.setPreferredSize(new java.awt.Dimension(110, 26));
        jtDni1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jtNombre1.setEditable(false);
        jtNombre1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtNombre1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jtCiudad1.setEditable(false);
        jtCiudad1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtCiudad1.setPreferredSize(new java.awt.Dimension(110, 26));
        jtCiudad1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("CIUDAD:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("TELEFONO:");

        jtTelefono1.setEditable(false);
        jtTelefono1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtTelefono1.setPreferredSize(new java.awt.Dimension(110, 26));
        jtTelefono1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jcantCoinc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcantCoinc.setText("0");

        jbSig.setText("SIGUIENTE>>");
        jbSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSigActionPerformed(evt);
            }
        });

        jbAnt.setText("ANTERIOR<<");
        jbAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(85, 85, 85)
                                            .addComponent(jcantCoinc)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(125, 125, 125)
                                            .addComponent(jtDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(77, 77, 77)
                                            .addComponent(jtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(83, 83, 83)
                                            .addComponent(jtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(64, 64, 64)
                                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(71, 71, 71)
                                            .addComponent(jtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(90, 90, 90)
                                            .addComponent(jtCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(jbSig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbAnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcantCoinc))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jbSig, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jtDni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(97, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInputActionPerformed



    }//GEN-LAST:event_jtInputActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
              
            if(!jtInput.getText().equals("")){
                
                ArrayList<Cliente> c; 
            
            switch(jComboBox.getSelectedIndex()){
                
                case 0:  c = MenuDirectorio.directorio.buscarClienteNombre(jtInput.getText());
                         if(!c.isEmpty()){
                         jcantCoinc.setText(String.valueOf( c.size()));
                         jtNombre1.setText(c.get(count).getNombre());
                         jtApellido1.setText(c.get(count).getApellido());
                         jtDni1.setText(String.valueOf( c.get(count).getDni()));
                         jtCiudad1.setText(c.get(count).getCiudad());
                         jtDireccion.setText(c.get(count).getDomicilio());
                         jtTelefono1.setText(c.get(count).getTelefono());
                         }else{
                             JOptionPane.showMessageDialog(this, "Apellido de cliente NO encontrado ");
                         }
                         break;
                case 1: c = MenuDirectorio.directorio.buscarClientes(jtInput.getText());
                         if(!c.isEmpty()){
                         jcantCoinc.setText(String.valueOf(c.size()));
                         jtNombre1.setText(c.get(count).getNombre());
                         jtApellido1.setText(c.get(count).getApellido());
                         jtDni1.setText(String.valueOf( c.get(count).getDni()));
                         jtCiudad1.setText(c.get(count).getCiudad());
                         jtDireccion.setText(c.get(count).getDomicilio());
                         jtTelefono1.setText(c.get(count).getTelefono());
                         }else{
                             JOptionPane.showMessageDialog(this, "No existe cliente en esa ciudad ");
                         }
                         break;
                case 2: Cliente t = MenuDirectorio.directorio.buscarTelefono(jtInput.getText());
                         if(t!=null){
                         jcantCoinc.setText("1");
                         jtNombre1.setText(t.getNombre());
                         jtApellido1.setText(t.getApellido());
                         jtDni1.setText(String.valueOf( t.getDni()));
                         jtCiudad1.setText(t.getCiudad());
                         jtDireccion.setText(t.getDomicilio());
                         jtTelefono1.setText(t.getTelefono());
                         }
                         else{
                          JOptionPane.showMessageDialog(this, "Numero de telefono inexistente");
                         }
            }
                      
            }
    
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
dispose();     
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
       
        
        
        
        
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jbSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSigActionPerformed
        
        if(jComboBox.getSelectedIndex()!=2){
        
        try{
             count++;
        jbBuscar.doClick();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No hay mas elementos por recorrer");
            count--;
        }
        }else{
             JOptionPane.showMessageDialog(this, "No hay mas elementos por recorrer");  
             }
    }//GEN-LAST:event_jbSigActionPerformed

    private void jtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellido1ActionPerformed

    }//GEN-LAST:event_jtApellido1ActionPerformed

    private void jbAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAntActionPerformed
        
        if(jComboBox.getSelectedIndex()!=2){
        try{
             count--;
        jbBuscar.doClick();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No hay mas elementos por recorrer");
            count++;
        }
        }else{
             JOptionPane.showMessageDialog(this, "No hay mas elementos por recorrer");  
             }
        
    }//GEN-LAST:event_jbAntActionPerformed
    
    
    private void clear() {
        jtApellido1.setText("");
        jtCiudad1.setText("");
        jtDireccion.setText("");
        jtTelefono1.setText("");
        jtDni1.setText("");
        jtNombre1.setText("");
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbAnt;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSig;
    private javax.swing.JLabel jcantCoinc;
    private javax.swing.JTextField jtApellido1;
    private javax.swing.JTextField jtCiudad1;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtDni1;
    private javax.swing.JTextField jtInput;
    private javax.swing.JTextField jtNombre1;
    private javax.swing.JTextField jtTelefono1;
    // End of variables declaration//GEN-END:variables
}
